# Generated by Django 5.0.4 on 2024-04-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
